[
      {'label': 0, 'value': '가스'} 
     ,{'label': 1, 'value': '건설기계설비'} 
     ,{'label': 2, 'value': '건설기계정비'} 
     ,{'label': 3, 'value': '건설배관분야'} 
     ,{'label': 4, 'value': '건설안전'} 
     ,{'label': 5, 'value': '건설재료시험'} 
     ,{'label': 6, 'value': '건축'} 
     ,{'label': 7, 'value': '건축목재시공'} 
     ,{'label': 8, 'value': '건축분야'} 
     ,{'label': 9, 'value': '건축설비'} 
     ,{'label': 10, 'value': '건축일반시공'} 
     ,{'label': 11, 'value': '게임그래픽전문가'} 
     ,{'label': 12, 'value': '게임기획전문가'} 
     ,{'label': 13, 'value': '게임프로그래밍전문가'} 
     ,{'label': 14, 'value': '경영분야'} 
     ,{'label': 15, 'value': '공조냉동기계'} 
     ,{'label': 16, 'value': '광산보안'} 
     ,{'label': 17, 'value': '광학'} 
     ,{'label': 18, 'value': '광해방지'} 
     ,{'label': 19, 'value': '광해방지분야'} 
     ,{'label': 20, 'value': '교통'} 
     ,{'label': 21, 'value': '국제의료관광코디네이터'} 
     ,{'label': 22, 'value': '궤도장비정비'} 
     ,{'label': 23, 'value': '귀금속가공'} 
     ,{'label': 24, 'value': '그린전동자동차'} 
     ,{'label': 25, 'value': '금속.재료분야'} 
     ,{'label': 26, 'value': '금속재료'} 
     ,{'label': 27, 'value': '금형.공작기계분야'} 
     ,{'label': 28, 'value': '금형제작'} 
     ,{'label': 29, 'value': '기계가공'} 
     ,{'label': 30, 'value': '기계설계'} 
     ,{'label': 31, 'value': '기계장비설비.설치분야'} 
     ,{'label': 32, 'value': '기계제작분야'} 
     ,{'label': 33, 'value': '기상'} 
     ,{'label': 34, 'value': '기상감정'} 
     ,{'label': 35, 'value': '농업기계'} 
     ,{'label': 36, 'value': '농업분야'} 
     ,{'label': 37, 'value': '농작업안전보건'} 
     ,{'label': 38, 'value': '누설비파괴검사'} 
     ,{'label': 39, 'value': '단조.주조분야'} 
     ,{'label': 40, 'value': '대기환경'} 
     ,{'label': 41, 'value': '도시.교통분야'} 
     ,{'label': 42, 'value': '도시계획'} 
     ,{'label': 43, 'value': '도장.도금분야'} 
     ,{'label': 44, 'value': '디자인분야'} 
     ,{'label': 45, 'value': '로봇기구개발'} 
     ,{'label': 46, 'value': '로봇소프트웨어개발'} 
     ,{'label': 47, 'value': '로봇하드웨어개발'} 
     ,{'label': 48, 'value': '멀티미디어콘텐츠제작전문가'} 
     ,{'label': 49, 'value': '목재.가구.공예분야'} 
     ,{'label': 50, 'value': '무선설비'} 
     ,{'label': 51, 'value': '미용장'} 
     ,{'label': 52, 'value': '바이오화학제품제조'} 
     ,{'label': 53, 'value': '방사선비파괴검사'} 
     ,{'label': 54, 'value': '방송.무선분야'} 
     ,{'label': 55, 'value': '방송통신'} 
     ,{'label': 56, 'value': '방재'} 
     ,{'label': 57, 'value': '배관'} 
     ,{'label': 58, 'value': '보건.의료분야'} 
     ,{'label': 59, 'value': '비서1급'} 
     ,{'label': 60, 'value': '비서2급'} 
     ,{'label': 61, 'value': '비서3급'} 
     ,{'label': 62, 'value': '비파괴검사분야'} 
     ,{'label': 63, 'value': '빅데이터분석'} 
     ,{'label': 64, 'value': '사무분야'} 
     ,{'label': 65, 'value': '사출금형설계'} 
     ,{'label': 66, 'value': '사회복지.종교분야'} 
     ,{'label': 67, 'value': '사회조사분석사1급'} 
     ,{'label': 68, 'value': '사회조사분석사2급'} 
     ,{'label': 69, 'value': '산림'} 
     ,{'label': 70, 'value': '산업안전'} 
     ,{'label': 71, 'value': '산업위생관리'} 
     ,{'label': 72, 'value': '생물분류(동물)'} 
     ,{'label': 73, 'value': '생물분류(식물)'} 
     ,{'label': 74, 'value': '생산관리분야'} 
     ,{'label': 75, 'value': '서비스·경험디자인'} 
     ,{'label': 76, 'value': '설비보전'} 
     ,{'label': 77, 'value': '섬유'} 
     ,{'label': 78, 'value': '섬유분야'} 
     ,{'label': 79, 'value': '소방설비(기계분야)'} 
     ,{'label': 80, 'value': '소방설비(전기분야)'} 
     ,{'label': 81, 'value': '소비자전문상담사1급'} 
     ,{'label': 82, 'value': '소비자전문상담사2급'} 
     ,{'label': 83, 'value': '소음진동'} 
     ,{'label': 84, 'value': '수산양식'} 
     ,{'label': 85, 'value': '수산제조'} 
     ,{'label': 86, 'value': '수질환경'} 
     ,{'label': 87, 'value': '숙박.여행.오락.스포츠분야'} 
     ,{'label': 88, 'value': '스포츠경영관리사'} 
     ,{'label': 89, 'value': '승강기'} 
     ,{'label': 90, 'value': '시각디자인'} 
     ,{'label': 91, 'value': '시설원예'} 
     ,{'label': 92, 'value': '식물보호'} 
     ,{'label': 93, 'value': '식육가공'} 
     ,{'label': 94, 'value': '식품'} 
     ,{'label': 95, 'value': '식품분야'} 
     ,{'label': 96, 'value': '신재생에너지발전설비(태양광)'} 
     ,{'label': 97, 'value': '실내건축'} 
     ,{'label': 98, 'value': '안전관리분야'} 
     ,{'label': 99, 'value': '압연'} 
     ,{'label': 100, 'value': '어업분야'} 
     ,{'label': 101, 'value': '어업생산관리'} 
     ,{'label': 102, 'value': '에너지.기상분야'} 
     ,{'label': 103, 'value': '에너지관리'} 
     ,{'label': 104, 'value': '영업.판매분야'} 
     ,{'label': 105, 'value': '온실가스관리'} 
     ,{'label': 106, 'value': '와전류비파괴검사'} 
     ,{'label': 107, 'value': '용접'} 
     ,{'label': 108, 'value': '용접분야'} 
     ,{'label': 109, 'value': '워드프로세서'} 
     ,{'label': 110, 'value': '원자력'} 
     ,{'label': 111, 'value': '위험물'} 
     ,{'label': 112, 'value': '위험물분야'} 
     ,{'label': 113, 'value': '유기농업'} 
     ,{'label': 114, 'value': '응용지질'} 
     ,{'label': 115, 'value': '의공'} 
     ,{'label': 116, 'value': '의류'} 
     ,{'label': 117, 'value': '이용.미용분야'} 
     ,{'label': 118, 'value': '이용장'} 
     ,{'label': 119, 'value': '인간공학'} 
     ,{'label': 120, 'value': '인쇄'} 
     ,{'label': 121, 'value': '인쇄.사진분야'} 
     ,{'label': 122, 'value': '일반기계'} 
     ,{'label': 123, 'value': '임베디드'} 
     ,{'label': 124, 'value': '임산가공'} 
     ,{'label': 125, 'value': '임상심리사1급'} 
     ,{'label': 126, 'value': '임상심리사2급'} 
     ,{'label': 127, 'value': '임업분야'} 
     ,{'label': 128, 'value': '임업종묘'} 
     ,{'label': 129, 'value': '자기비파괴검사'} 
     ,{'label': 130, 'value': '자동차분야'} 
     ,{'label': 131, 'value': '자동차정비'} 
     ,{'label': 132, 'value': '자연생태복원'} 
     ,{'label': 133, 'value': '잠수'} 
     ,{'label': 134, 'value': '전기'} 
     ,{'label': 135, 'value': '전기공사'} 
     ,{'label': 136, 'value': '전기분야'} 
     ,{'label': 137, 'value': '전기철도'} 
     ,{'label': 138, 'value': '전산회계운용사1급'} 
     ,{'label': 139, 'value': '전산회계운용사2급'} 
     ,{'label': 140, 'value': '전산회계운용사3급'} 
     ,{'label': 141, 'value': '전자'} 
     ,{'label': 142, 'value': '전자계산기'} 
     ,{'label': 143, 'value': '전자계산기조직응용'} 
     ,{'label': 144, 'value': '전자기기'} 
     ,{'label': 145, 'value': '전자분야'} 
     ,{'label': 146, 'value': '전자상거래관리사1급'} 
     ,{'label': 147, 'value': '전자상거래관리사2급'} 
     ,{'label': 148, 'value': '전자상거래운용사'} 
     ,{'label': 149, 'value': '전파전자통신'} 
     ,{'label': 150, 'value': '정밀화학'} 
     ,{'label': 151, 'value': '정보기술분야'} 
     ,{'label': 152, 'value': '정보보안'} 
     ,{'label': 153, 'value': '정보처리'} 
     ,{'label': 154, 'value': '정보통신'} 
     ,{'label': 155, 'value': '제강'} 
     ,{'label': 156, 'value': '제과'} 
     ,{'label': 157, 'value': '제과.제빵분야'} 
     ,{'label': 158, 'value': '제선'} 
     ,{'label': 159, 'value': '제품디자인'} 
     ,{'label': 160, 'value': '조경'} 
     ,{'label': 161, 'value': '조경분야'} 
     ,{'label': 162, 'value': '조리'} 
     ,{'label': 163, 'value': '조리분야'} 
     ,{'label': 164, 'value': '조선'} 
     ,{'label': 165, 'value': '조선분야'} 
     ,{'label': 166, 'value': '종자'} 
     ,{'label': 167, 'value': '주조'} 
     ,{'label': 168, 'value': '지적'} 
     ,{'label': 169, 'value': '직업상담사1급'} 
     ,{'label': 170, 'value': '직업상담사2급'} 
     ,{'label': 171, 'value': '채광분야'} 
     ,{'label': 172, 'value': '철도분야'} 
     ,{'label': 173, 'value': '철도신호'} 
     ,{'label': 174, 'value': '철도차량'} 
     ,{'label': 175, 'value': '철도차량정비'} 
     ,{'label': 176, 'value': '철도토목'} 
     ,{'label': 177, 'value': '초음파비파괴검사'} 
     ,{'label': 178, 'value': '축산'} 
     ,{'label': 179, 'value': '축산분야'} 
     ,{'label': 180, 'value': '측량및지형공간정보'} 
     ,{'label': 181, 'value': '침투비파괴검사'} 
     ,{'label': 182, 'value': '컨벤션기획사1급'} 
     ,{'label': 183, 'value': '컨벤션기획사2급'} 
     ,{'label': 184, 'value': '컬러리스트'} 
     ,{'label': 185, 'value': '컴퓨터활용능력1급'} 
     ,{'label': 186, 'value': '컴퓨터활용능력2급'} 
     ,{'label': 187, 'value': '콘크리트'} 
     ,{'label': 188, 'value': '텔레마케팅관리사'} 
     ,{'label': 189, 'value': '토목'} 
     ,{'label': 190, 'value': '토목분야'} 
     ,{'label': 191, 'value': '토양환경'} 
     ,{'label': 192, 'value': '통신분야'} 
     ,{'label': 193, 'value': '통신설비'} 
     ,{'label': 194, 'value': '판금.제관.새시분야'} 
     ,{'label': 195, 'value': '판금제관'} 
     ,{'label': 196, 'value': '폐기물처리'} 
     ,{'label': 197, 'value': '포장'} 
     ,{'label': 198, 'value': '표면처리'} 
     ,{'label': 199, 'value': '품질경영'} 
     ,{'label': 200, 'value': '프레스금형설계'} 
     ,{'label': 201, 'value': '한글속기1급'} 
     ,{'label': 202, 'value': '한글속기2급'} 
     ,{'label': 203, 'value': '한글속기3급'} 
     ,{'label': 204, 'value': '항공'} 
     ,{'label': 205, 'value': '항공분야'} 
     ,{'label': 206, 'value': '항로표지'} 
     ,{'label': 207, 'value': '해양공학'} 
     ,{'label': 208, 'value': '해양자원개발'} 
     ,{'label': 209, 'value': '해양환경'} 
     ,{'label': 210, 'value': '화공'} 
     ,{'label': 211, 'value': '화공분야'} 
     ,{'label': 212, 'value': '화약류관리'} 
     ,{'label': 213, 'value': '화약류제조'} 
     ,{'label': 214, 'value': '화재감식평가'} 
     ,{'label': 215, 'value': '화학분석'} 
     ,{'label': 216, 'value': '화훼장식'} 
     ,{'label': 217, 'value': '환경분야'} 
     ,{'label': 218, 'value': '환경위해관리'} 
     ,{'label': 219, 'value': '회계분야'}
 ]